### PR TITLE
Avoid raw URL in readme.

### PR DESCRIPTION
**Pull request by adlerjohn**

### CODE REVIEW

**Comment by tzdybal** [comment]
Could you provide any context? What's the difference, and why it's bad to use "raw URLs"?

**Comment by adlerjohn** [comment]
https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md034---bare-url-used

> Rationale: Without angle brackets, the URL isn't converted into a link by many markdown parsers.

**Comment by liamsi** [comment]
Maybe we should simply add markdownlint?

**Comment by adlerjohn** [comment]
Orthogonally to this PR, yes

**Review by tzdybal — APPROVED** [review]

**Pull request merged**
