### PR TITLE
Update optimint to be compatible with Tendermint v0.35.3

### PR DESCRIPTION
**Pull request by tzdybal**
Because of massive refactoring in Tendermint, new version is actually less-dependent on Tendermint (see: #37).
As a bonus of this update mempool, block indexer and transaction indexer are updated.

Resolves: #191

### CODE REVIEW

**Comment by adlerjohn** [comment]
Is this good to go?

**Comment by tzdybal** [comment]
> Is this good to go? (Accidentally hit the merge from master button grimacing sorry)

There's a list of missing features (https://github.com/celestiaorg/optimint/issues/358). But IMHO we could merge this, and then follow up. 

I'll comment what parts are "copied" and what are "changed".

**Comment by tzdybal** [comment]
> Is this still blocking #355 , #356 , and #357 ?

Yes, because the only reason to introduce those RPC methods is to make optimint compatible with tendermint v0.35.x.

**Comment by liamsi** [comment]
I think you can close this and instead rip out this part
> Because of massive refactoring in Tendermint, new version is actually less-dependent on Tendermint

and other improvements.

**Comment by jbowen93** [comment]
Tendermint v0.35 is dead so we can close this.

**Pull request closed without merging**
