### PR TITLE
Fix multiple bugs for Ethermint

### LINKED ISSUE #294: `LoadBlockByHash` doesn't load `LastCommit`
`SaveBlock` saves a block in a batch consisting of: block data, commit, indexing information.
`LoadBlockByHash` restores block data, but does not fill `LastCommit` field of the block - this has to be fixed.

### LINKED ISSUE #295: After conversion to ABCI Block, ValidatorsHash is nil
After converting Optimint Block into ABCI Block (see: [conv/abci/block.go:33](https://github.com/celestiaorg/optimint/blob/main/conv/abci/block.go#L33)), `ValidatorsHash` is `nil`.

Because of that, `Hash` method for the block object returns `nil`.

### LINKED ISSUE #297: Validator updates from `ResponseInitChain` are not processed
`ResponseInitChain` contains `Validators` field, which is currently ignored.

Optimint has to support this way of updating validator set.

This was discovered with Ethermint integration test suite.

ref: https://github.com/celestiaorg/evmos/issues/11

### LINKED ISSUE #301: ABCI Header hash should be used
Currently Optimint hash it's own header object for hashing. Default way of operation with 'outside world' are ABCI interface and Tendermint RPC. For those APIs, objects are translated to ABCI form. Methods like `BlockByHash` should use hash of ABCI Block/Header.

Simple example: user has a block header, creates a hash, and calls `BlockByHash`. Optimint is not able to find this hash, as internally hash of Optimint's Header object was used to store data in store.

Possible solutions to this are:
 - save extra mapping between ABCI Header hash and Optimint Header hash
 - use ABCI header hash everywhere (on `Header.Hash()` convert to ABCI header and return it's hash)

### LINKED ISSUE #304: `ToABCIBlock` set's `DataHash` incorrectly
`ToABCIBlock` generates `DataHash` instead of copying it from Optimint header. This is a bug, and should be fixed.

Faulty line:
https://github.com/celestiaorg/optimint/blob/5d8f737d305b7ebe7ccc630ee141b2d172f0a112/conv/abci/block.go#L94

### PR DESCRIPTION
**Pull request by tzdybal**
:onion: 

Resolves #294
Resolves #295
Resolves #297
Resolves #301
Resolves #304

Ethermint integration tests are passing using this branch.

### CODE REVIEW

**Review by jbowen93 — COMMENTED** [review]
LGTM on reading it. I want to pull the code and do a quick test on the ephemeral cluster before approval.

**Review by adlerjohn — COMMENTED** [review]
Nothing stands out as wrong, will defer to @jbowen93 actually trying it out

**Comment by jbowen93** [comment]
Confirming that both `cast block latest` which calls `eth_getBlockByNumber` and `cast tx <tx-hash>` which calls `eth_getTransactionByHash` both work now.

**Comment by jbowen93** [comment]
I don't think I have approval permissions

**Review by adlerjohn — APPROVED** [review]

**Comment by tzdybal** [comment]
> Confirming that both `cast block latest` which calls `eth_getBlockByNumber` and `cast tx <tx-hash>` which calls `eth_getTransactionByHash` both work now.

And what about contract deployment?

**Comment by jbowen93** [comment]
> > Confirming that both `cast block latest` which calls `eth_getBlockByNumber` and `cast tx <tx-hash>` which calls `eth_getTransactionByHash` both work now.
> 
> And what about contract deployment?

Contract deployment still fails. The log returned from Evmos is
```
2:27AM INF ABCIQuery data=0A3365766D6F7376616C636F6E7331706A6370346A74356C767279737134707072363876616C613673327064793672363265343332 module=events path=/ethermint.evm.v1.Query/ValidatorAccount result={"code":111222,"codespace":"undefined","height":"0","index":"0","info":"","key":null,"log":"panic message redacted to hide potentially sensitive system info: panic","proofOps":null,"value":null}
```

I'll step through this and see what the actual error is.

**Comment by jbowen93** [comment]
The call to get a validator that eventually reaches here (https://github.com/jbowen93/ethermint/blob/main/x/evm/keeper/grpc_query.go#L105) doesn't find the validator.

**Comment by jbowen93** [comment]
I'd like to merge this since it's an improvement to the existing functionality. We can track the Validator call issue separately.

**Comment by tzdybal** [comment]
Created #306 as follow-up issue.

**Pull request merged**
