### PR TITLE
fix: saving block height after committing validators to db

### LINKED ISSUE #462: `TestValidatorSetHandling` is flaky
`TestValidatorSetHandling` is flaky - it sometimes fails like this:
```
    client_test.go:709: 
        	Error Trace:	client_test.go:709
        	Error:      	Received unexpected error:
        	            	failed to load validators for height 13: key not found
        	Test:       	TestValidatorSetHandling
I[2022-07-01|21:21:07.297] indexed block                                module=txindex height=13
    client_test.go:710: 
        	Error Trace:	client_test.go:710
        	Error:      	Expected value not to be nil.
        	Test:       	TestValidatorSetHandling
--- FAIL: TestValidatorSetHandling (0.13s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x11fa485]

goroutine 1972 [running]:
testing.tRunner.func1.2({0x134e020, 0x23f2590})
	/usr/lib/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/lib/go/src/testing/testing.go:1392 +0x39f
panic({0x134e020, 0x23f2590})
	/usr/lib/go/src/runtime/panic.go:838 +0x207
github.com/celestiaorg/optimint/rpc/client.TestValidatorSetHandling(0xc05f6a7380?)
	/home/tomek/devel/celestia/optimint/rpc/client/client_test.go:711 +0x1625
testing.tRunner(0xc05f6a7380, 0x183fa70)
	/usr/lib/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1486 +0x35f
```

### PR DESCRIPTION
**Pull request by distractedm1nd**
Would resolve #462 . Is there any concerns about this change? The handling may change when #457 is investigated anyways

### CODE REVIEW

**Comment by distractedm1nd** [comment]
The case is definitely that (when it flakes) we read the validators before we commit them to the db - you can confirm this by logging the reads and writes. Doesn't flake anymore with this fix, so the biggest question is just if changing the order of operations has adverse effects?

**Comment by tzdybal** [comment]
@jbowen93 WDYT? Is there any particular reason why height was stored before commit?

**Review by adlerjohn — COMMENTED** [review]
Fundamentally, this is resolving a data race, no? This might resolve a single instance of the race, but there should be some sort of static check/guarantee that things that need to be committed to the db atomically are committed atomically.

**Comment by distractedm1nd** [comment]
I agree, but I don't think investigating other data races, or adding tooling to detect it, is really in the scope of this PR, right?

**Comment by adlerjohn** [comment]
> is really in the scope of this PR, right?

Nope, can be left for future work.

**Review by tzdybal — APPROVED** [review]
Let's merge this for now. It fixes the bug, and shouldn't introduce completely new issues.
I also created https://github.com/celestiaorg/optimint/issues/477, which should resolve the core issue here.

**Pull request merged**
