### PR TITLE
Remove extra variable

### PR DESCRIPTION
**Pull request by Raneet10**
Currently, in [`BlockSearch`](https://github.com/celestiaorg/optimint/blob/566d72877da31350062a99cef5bc2d61b0bf32e6/rpc/client/client.go#L510) RPC method we use `pageResults` to store the paginated block heights. This is not needed.

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
Is there a reason `go.sum` and `go.mod` were modified?

**Comment by tzdybal** [comment]
> Is there a reason `go.sum` and `go.mod` were modified?

There is no reason, and it should be reverted. Let's update deps in separate PR.

**Comment by Raneet10** [comment]
> Is there a reason `go.sum` and `go.mod` were modified?

Yep, this wasn't intentional. I've reverted the changes.

**Review by tzdybal — APPROVED** [review]
LGTM

**Pull request merged**
