### PR TITLE
deps: update to go-libp2p v0.21.0

### PR DESCRIPTION
**Pull request by tzdybal**

### CODE REVIEW

**Review by jbowen93 — DISMISSED** [review]

**Review by Wondertan — APPROVED** [review]
As long as optimint does not use Swarm notifications, this update is frictionless.

**Comment by tzdybal** [comment]
eh, I forcepushed the changes, which discarded approvals :(

**Comment by Wondertan** [comment]
@tzdybal, rebase?

**Comment by tzdybal** [comment]
yes, exactly

**Review by Wondertan — APPROVED** [review]
Ok

**Pull request merged**
