### PR TITLE
Remove changelog checker.

### PR DESCRIPTION
**Pull request by adlerjohn**
## Description

Remove changelog checker since it's a giant waste of engineering time in favor of GitHub automatic changelogs.

ref https://github.com/celestiaorg/celestia-node/pull/500

### CODE REVIEW

**Comment by adlerjohn** [comment]
> will increase coverage by 0.02%.

Looks like Codecov is next on the chopping block.

**Comment by tzdybal** [comment]
So you say we don't want to have CHANGELOG.md file an use only releases page on github?

**Comment by adlerjohn** [comment]
Primarily the pending changelog, since it requires additional work every time and can lead to merge conflicts. The per-release changelog is much lower overhead and could stay if you prefer it that way, though would be duplicative to automatic github changelogs. I'll defer to you on this one @tzdybal

**Comment by adlerjohn** [comment]
Restored changelog @tzdybal

**Review by tzdybal — APPROVED** [review]

**Pull request merged**
